#include "TinyCPUBackend.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/raw_ostream.h"

// opcode enum generated by tinytblgen from TinyCPU.td
#define GET_INST_ENUM
#include "TinyCPU.inc"

struct InstInfo { const char *Mnemonic; unsigned Opcode; unsigned NumOps; };
static const InstInfo InstTable[NUM_TINYCPU_INSTS] = {
#define GET_INST_INFO
#include "TinyCPU.inc"
};

// map an LLVM IR opcode to the nearest TinyCPU mnemonic
static const char *mapOpcode(unsigned LLVMOpc) {
    using llvm::Instruction;
    switch (LLVMOpc) {
    case Instruction::Add:   return InstTable[ADD].Mnemonic;
    case Instruction::Sub:   return InstTable[SUB].Mnemonic;
    case Instruction::Mul:   return InstTable[MUL].Mnemonic;
    case Instruction::Load:  return InstTable[LD].Mnemonic;
    case Instruction::Store: return InstTable[ST].Mnemonic;
    case Instruction::Br:    return InstTable[BR].Mnemonic;
    case Instruction::Ret:   return InstTable[RET].Mnemonic;
    default:                 return nullptr;
    }
}

void tinyjs::emitTinyCPU(llvm::Module *M, llvm::StringRef OutPath) {
    std::error_code EC;
    llvm::raw_fd_ostream OS(OutPath, EC, llvm::sys::fs::OF_Text);
    if (EC) {
        llvm::errs() << "Error writing " << OutPath << ": " << EC.message() << "\n";
        return;
    }

    OS << "; TinyCPU assembly -- " << M->getName() << "\n\n";

    for (auto &F : *M) {
        if (F.isDeclaration()) continue;
        OS << F.getName() << ":\n";
        for (auto &BB : F) {
            OS << "  ." << BB.getName() << ":\n";
            for (auto &I : BB) {
                const char *Mnemonic = mapOpcode(I.getOpcode());
                if (Mnemonic)
                    OS << "    " << Mnemonic << "\n";
                else
                    OS << "    ; " << I.getOpcodeName() << "\n";
            }
        }
        OS << "\n";
    }

    llvm::outs() << "TinyCPU assembly written to " << OutPath << "\n";
}
